spring:
  resources:
    static-locations: file:src/main/resources/static/

  data:
    postgres:
      host: 127.0.0.1
      port: 5432
      database: mydb
      username: postgres
      password: test

  profiles:
    active: test


